version: "3.8"
services:
        
        tomcat:
                build:
                        context: ./tomcat
                        dockerfile: Dockerfile
                networks:
        nginx:
                depends_on:
                        - tomcat
                image: 'nginx:alpine'
                restart: always
                volumes:
                        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
                ports:
                        - '80:80'

                links:
                        - tomcat
        calculador:
                build:
                        context: ./procesosCalcularRiesgo
                        dockerfile: Dockerfile
